FROM python:3.10.12-slim

WORKDIR /app

COPY requirements.logger.txt .

RUN apt-get update && apt-get install -y libpq-dev gcc \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.logger.txt

COPY . .

ENV PYTHONPATH=/app

CMD ["python", "src/main.py"]
    