FROM python:3.10.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*


COPY requirements.txt /app/
COPY requirements.tests.txt /app/

RUN pip install --no-cache-dir -r requirements.tests.txt

COPY . .

ENV PYTHONPATH=/app

CMD ["pytest", "tests/", "-v", "-s", "-o", "log_cli=true", "--log-cli-level=INFO", "--color=yes"]