# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mlflow_probs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mlflow_probs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12mlflow_probs.proto\x12\x0cmlflow_probs\" \n\x0ePredictionList\x12\x0e\n\x06values\x18\x01 \x03(\x02\"\x93\x01\n\x0bMlflowProbs\x12*\n\x04pred\x18\x01 \x03(\x0b\x32\x1c.mlflow_probs.PredictionList\x12\x13\n\x0b\x62\x61tch_index\x18\x02 \x01(\x05\x12\x11\n\tclient_id\x18\x03 \x01(\t\x12\x12\n\nsession_id\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x12\x0e\n\x06labels\x18\x06 \x03(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mlflow_probs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTIONLIST']._serialized_start=36
  _globals['_PREDICTIONLIST']._serialized_end=68
  _globals['_MLFLOWPROBS']._serialized_start=71
  _globals['_MLFLOWPROBS']._serialized_end=218
# @@protoc_insertion_point(module_scope)
